# Generated by Django 5.0.7 on 2024-07-23 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('JK', 'jamu&kashmir'), ('HM', 'Himachal Pradesh'), ('CH', 'Chandighar'), ('HR', 'Haryana'), ('UP', 'Utar Pradesh'), ('BH', 'Bihar'), ('WB', 'West Bangal'), ('OS', 'Odisha'), ('KR', 'Kerela'), ('TM', 'Tamil Nadu'), ('AM', 'assam'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('HM', 'Himaliya'), ('MN', 'Manipur'), ('SK', 'Skkim'), ('LH', 'Leh'), ('LD', 'ladahk'), ('AB', 'Andman Nicobar'), ('GA', 'Goa'), ('MP', 'Madhiya Pradesh'), ('MH', 'Maharastra'), ('UT', 'Utrakhand')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
